### ISSUE TITLE
Projects needs a new maintainer. 

### ISSUE THREAD

**Issue by makasim** [sroze/messenger-enqueue-transport#30]

**Comment by drgomesp** [comment]
I can take ownership of it.

**Comment by makasim** [comment]
@drgomesp sent you an invite. Welcome!

**Comment by vklymniuk** [comment]
Still need free hands?

**Comment by drgomesp** [comment]
We can always use a free set of hangs @vklymniuk

**Comment by shulard** [comment]
Hello guys, I'm interested to be part of the team if there is multiple persons required to take the lead.

**Comment by sroze** [comment]
Sounds great. There are plenty of small issues to resolve :)

**Comment by devrck** [comment]
@sroze this can be closed i think :smile:

**Comment by weaverryan** [comment]
Agreed!
