### ISSUE TITLE
Stable Messenger 4.3 support

### ISSUE THREAD

**Issue by danizord** [sroze/messenger-enqueue-transport#69]
I see that the commit https://github.com/sroze/messenger-enqueue-transport/commit/fbcaa00ec5714cfc01b70f0114d189351a5e8286 aims to add support for Messenger 4.3, but there's no tag for it yet.

Are there any missing tasks for complete 4.3 support?

**Comment by rumours86** [comment]
use command:
`composer require enqueue/messenger-adapter:dev-master`

**Comment by rumours86** [comment]
it is does not work for me (

**Comment by desmax** [comment]
@rumours86 try point to specific commit `"enqueue/messenger-adapter": "dev-master#fbcaa00ec5714cfc01b70f0114d189351a5e8286"`

**Comment by desmax** [comment]
breaks with message `The message could not be acknowledged because it does not have job set`

**Comment by desmax** [comment]
@sroze your attention please

**Comment by rumours86** [comment]
@keulinho can you make new release?

**Comment by sroze** [comment]
[0.3.0](https://github.com/sroze/messenger-enqueue-transport/releases/tag/0.3.0) has been tagged :)
