### ISSUE TITLE
SQS + Symfony 4.3 deletion fail

### ISSUE THREAD

**Issue by zeliard91** [sroze/messenger-enqueue-transport#71]
Hi,

The deletion of Amazon SQS messages is not working anymore with the new `QueueInteropTransport` inherited from Symfony 4.3.

`Interop\Queue\Message\SqsMessage` need to have the attribute `receiptHandle` defined in order to be deleted.

This worked before 4.3 because the same object was received and sent by the transport but now, as the messages are reconstructed with `QueueInteropTransport::encodeMessage` they loose this attribute.

Do you have any idea how this could be fixed ?

Thanks.

**Comment by poliander** [comment]
This may affect other transports, too? (In my case enqueue/fs still works while enqueue/redis doesn't, but I am not sure whether this is the same problem as @zeliard91 described)

**Comment by hoangnd25** [comment]
Hi,

I'm having similar issue with `GpsMessage` where `nativeMessage` is missing due to the message being reconstructed via `QueueInteropTransport::encodeMessage`

I think this is also breaking KafkaMessage #74 

Is there any chance we could just skip the encoder for now?

**Comment by mikeymclellan** [comment]
In the meantime, I've downgraded to `"enqueue/messenger-adapter": "^0.2.2"`

**Comment by tristanbes** [comment]
What's the status of this report ? what's the recommendation if we're using SF4.3+ ?

**Comment by Matth--** [comment]
@tristanbes the 0.3.1 release has the fix for ack/rejecting messages. I think this issue can be closed

https://github.com/sroze/messenger-enqueue-transport/releases/tag/0.3.1

**Comment by tristanbes** [comment]
Thanks :)

**Comment by Matth--** [comment]
I can confirm the 0.3.1 and 0.3.2 release work with ack and nack.

@zeliard91 this issue can be closed

**Comment by zeliard91** [comment]
OK thanks you, I close the issue
